language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  - nightly

env:
  global:
  - NO_STYLE=1

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: NO_STYLE=0
  allow_failures:
    - php: nightly

before_install:
  - if [ $NO_STYLE = 1 ]; travis_retry composer remove friendsofphp/php-cs-fixer --no-interaction --no-update; fi

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit
