language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  - nightly

env:
- STYLE=false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: STYLE=true
  allow_failures:
    - php: nightly

before_install:
  - if [ $STYLE = false ]; then travis_retry composer remove friendsofphp/php-cs-fixer --dev --no-interaction --no-update; fi

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit
