language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  - nightly

env:
  global:
  - NO_STYLE=true

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: NO_STYLE=false
  allow_failures:
    - php: nightly

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit

before_install: $NO_STYLE && composer remove friendsofphp/php-cs-fixer --dev
