language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  - nightly

dist: trusty

matrix:
  include:
    - php: 5.3
      dist: precise
  allow_failures:
    - php: nightly

script: vendor/bin/phpunit tests/test.php
install: travis_retry composer install --prefer-dist --no-interaction --no-suggest
