language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: nightly
    - php: 5.3

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit

